name: handle
description: A simple library for composing HTTP clients, creating services to make HTTP requests.
version: 0.3.2+1
repository: https://github.com/predatorx7/handle

environment:
  sdk: '>=3.0.0 <4.0.0'

topics:
 - network
 - http
 - rest
 - client
 - rest

dependencies:
  collection: ^1.0.0
  http: ">=0.13.0 <2.0.0"
  meta: ^1.0.0
  quiver: ^3.0.0

dev_dependencies:
  benchmark_harness: ^2.2.1
  build_runner: ^2.3.3
  lints: ^2.0.0
  mockito: ^5.4.0
  test: ^1.21.0
  http_client_conformance_tests:
    git: 
      url: https://github.com/dart-lang/http.git
      path: pkgs/http_client_conformance_tests/
      ref: ba84ac0
